name: ai-stm-gpu
channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- pytorch
- torchvision
- torchaudio

# Once GPU/CUDA is known (One of the below):
# - pytorch-cuda=12.1
# or
# - pytorch-cuda=11.8